src/Entity/Cms.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

#[ORM\Table(name: 'cms')]
#[ORM\Entity(repositoryClass: 'App\Repository\CmsRepository')]
class Cms implements TranslatableInterface
{
    use TranslatableTrait;

    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private $id;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->translate()->getTitle();
    }

    public function getContent()
    {
        return $this->translate()->getContent();
    }

    public function getSlug()
    {
        return $this->translate()->getSlug();
    }
}

src/Entity/Donation.php
<?php

namespace App\Entity;

use App\Repository\DonationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;

#[ORM\Entity(repositoryClass: DonationRepository::class)]
#[ORM\Index(name: "transaction_idx", columns: ["transaction"])]
#[Gedmo\Loggable]
class Donation implements TimestampableInterface
{
    use TimestampableTrait;

    const STATUS_PUNCTUAL_NOT_VALID = 0;
    const STATUS_PUNCTUAL_VALID = 1;
    const STATUS_IN_PROGRESS = 42;   // TODO Keep only if used in old site imported data ?
    const STATUS_MONTHLY_NOT_VALID = 100;
    const STATUS_MONTHLY_VALID = 101;
    const STATUS_MONTHLY_HANDED = 102; // TODO Keep only if used in old site imported data ?
    //const STATUS_MONTHLY_CANCELLED = 103;

    const PAYMENT_METHOD_CB = 1;
    const PAYMENT_METHOD_CHECK = 2;
    const PAYMENT_METHOD_BANKWIRE = 3;
    const PAYMENT_METHOD_CASH = 4;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'donations')]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $user = null;

    #[ORM\Column]
    #[Gedmo\Versioned]
    private ?int $status = null;

    #[ORM\Column(length: 255)]
    private ?string $locale = 'fr';

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $amount = null;

    #[ORM\Column]
    private ?int $paymentMethod = null;

    #[ORM\ManyToOne(inversedBy: 'donations')]
    private ?UserBankAlias $userBankAlias = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $transaction = null;

    #[ORM\Column]
    private ?bool $userTotalCumulUpdated = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getStatusString(): ?string
    {
        switch ($this->getStatus()) {
            case self::STATUS_PUNCTUAL_NOT_VALID:
                return 'donation.status.punctual_not_valid';
            case self::STATUS_PUNCTUAL_VALID:
                return 'donation.status.punctual_valid';
            case self::STATUS_IN_PROGRESS:
                return 'donation.status.in_progress';
            case self::STATUS_MONTHLY_NOT_VALID:
                return 'donation.status.monthly_not_valid';
            case self::STATUS_MONTHLY_VALID:
                return 'donation.status.monthly_valid';
            case self::STATUS_MONTHLY_HANDED:
                return 'donation.status.monthly_handed';
            //case self::STATUS_MONTHLY_CANCELLED:
            //    return 'donation.status.monthly_cancelled';
            default:
                return null;
        }
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): static
    {
        $this->locale = $locale;

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getPaymentMethod(): ?int
    {
        return $this->paymentMethod;
    }

    public function setPaymentMethod(int $paymentMethod): static
    {
        $this->paymentMethod = $paymentMethod;

        return $this;
    }

    public function getPaymentMethodString(): ?string
    {
        switch ($this->getPaymentMethod()) {
            case self::PAYMENT_METHOD_CB:
                return 'donation.payment_method.cb';
            case self::PAYMENT_METHOD_CHECK:
                return 'donation.payment_method.check';
            case self::PAYMENT_METHOD_BANKWIRE:
                return 'donation.payment_method.bankwire';
            case self::PAYMENT_METHOD_CASH:
                return 'donation.payment_method.cash';
            default:
                return null;
        }
    }

    public function getExportData()
    {
        return [
            'fields.date' => $this->getCreatedAt(),
            'fields.user' => $this->getUser(),
            'fields.amount' => $this->getAmount(),
            'fields.status' => $this->getStatusString(),
            'fields.payment_method' => $this->getPaymentMethodString(),
        ];
    }

    public function getUserBankAlias(): ?UserBankAlias
    {
        return $this->userBankAlias;
    }

    public function setUserBankAlias(?UserBankAlias $userBankAlias): static
    {
        $this->userBankAlias = $userBankAlias;

        return $this;
    }

    public function getTransaction(): ?string
    {
        return $this->transaction;
    }

    public function setTransaction(?string $transaction): static
    {
        $this->transaction = $transaction;

        return $this;
    }

    public function isUserTotalCumulUpdated(): ?bool
    {
        return $this->userTotalCumulUpdated;
    }

    public function setUserTotalCumulUpdated(bool $userTotalCumulUpdated): static
    {
        $this->userTotalCumulUpdated = $userTotalCumulUpdated;

        return $this;
    }
}

src/Entity/Gift.php
<?php

namespace App\Entity;

use App\Repository\GiftRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: GiftRepository::class)]
#[Vich\Uploadable]
class Gift implements TimestampableInterface, TranslatableInterface
{
    use TimestampableTrait;
    use TranslatableTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(mappedBy: 'gift', targetEntity: GiftVariation::class, cascade: ['remove'])]
    private Collection $variations;

    #[ORM\Column]
    private ?int $donationAmountNeeded = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'gift', fileNameProperty: 'image')]
    private $imageFile;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image2 = null;

    #[Vich\UploadableField(mapping: 'gift', fileNameProperty: 'image2')]
    private $image2File;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $refImport = null;

    #[ORM\OneToMany(mappedBy: 'gift', targetEntity: Compensation::class)]
    private Collection $compensations;

    #[ORM\Column]
    private ?bool $active = true;

    public function __construct()
    {
        $this->variations = new ArrayCollection();
        $this->compensations = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->translate()->getName();
    }

    public function getDescription(): ?string
    {
        return $this->translate()->getDescription();
    }

    /**
     * @return Collection<int, GiftVariation>
     */
    public function getVariations(): Collection
    {
        return $this->variations;
    }

    public function addVariation(GiftVariation $variation): static
    {
        if (!$this->variations->contains($variation)) {
            $this->variations->add($variation);
            $variation->setGift($this);
        }

        return $this;
    }

    public function removeVariation(GiftVariation $variation): static
    {
        if ($this->variations->removeElement($variation)) {
            // set the owning side to null (unless already changed)
            if ($variation->getGift() === $this) {
                $variation->setGift(null);
            }
        }

        return $this;
    }

    public function getDonationAmountNeeded(): ?int
    {
        return $this->donationAmountNeeded;
    }

    public function setDonationAmountNeeded(int $donationAmountNeeded): static
    {
        $this->donationAmountNeeded = $donationAmountNeeded;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
        if ($imageFile) {
            $this->setUpdatedAt(new DateTime());
        }
        return $this;
    }

    public function getImage2(): ?string
    {
        return $this->image2;
    }

    public function setImage2(?string $image2): self
    {
        $this->image2 = $image2;

        return $this;
    }

    public function getImage2File()
    {
        return $this->image2File;
    }

    public function setImage2File($image2File)
    {
        $this->image2File = $image2File;
        if ($image2File) {
            $this->setUpdatedAt(new DateTime());
        }
        return $this;
    }

    public function getRefImport(): ?string
    {
        return $this->refImport;
    }

    public function setRefImport(?string $refImport): static
    {
        $this->refImport = $refImport;

        return $this;
    }

    /**
     * @return Collection<int, Compensation>
     */
    public function getCompensations(): Collection
    {
        return $this->compensations;
    }

    public function addCompensation(Compensation $compensation): static
    {
        if (!$this->compensations->contains($compensation)) {
            $this->compensations->add($compensation);
            $compensation->setGift($this);
        }

        return $this;
    }

    public function removeCompensation(Compensation $compensation): static
    {
        if ($this->compensations->removeElement($compensation)) {
            // set the owning side to null (unless already changed)
            if ($compensation->getGift() === $this) {
                $compensation->setGift(null);
            }
        }

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): static
    {
        $this->active = $active;

        return $this;
    }
}

src/Controller/Front/CmsController.php
<?php

namespace App\Controller\Front;

use App\Entity\CmsTranslation;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class CmsController extends AbstractController
{
    #[Route("/{_locale<%app.locales%>}/cms/{slug}", name: "cms")]
    public function cms(CmsTranslation $cmsTranslation)
    {
        return $this->render('front/cms.html.twig', [
            'bodyClass' => 'cms',
            'cms' => $cmsTranslation,
        ]);
    }
}

src/Controller/Front/DonationController.php
<?php

namespace App\Controller\Front;

use App\Entity\Donation;
use App\Entity\EmailLog;
use App\Entity\UserBankAlias;
use App\Service\MailerService;
use App\Util\PaymentServiceInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

class DonationController extends AbstractController
{
    public function __construct(
        private PaymentServiceInterface $paymentService,
        private EntityManagerInterface  $entityManager,
        private MailerService           $mailerService,
        private TranslatorInterface     $translator
    )
    {

    }

    #[Route('/{_locale<%app.locales%>}/donation', name: 'donation')]
    public function donation(Request $request)
    {
        $session = $request->getSession();
        if ($request->get('free-amount') || $request->get('amount')) {
            $session->set('amount', (int) ($request->get('free-amount') ?: $request->get('amount')));
            $session->set('monthly', (bool) $request->get('monthly'));
        }
        if (!$session->get('amount')) {
            return $this->redirectToRoute('index');
        }
        return $this->render('front/donation/donation.html.twig', [
            'amount' => $session->get('amount'),
            'monthly' => $session->get('monthly'),
        ]);
    }

    #[Route('/{_locale<%app.locales%>}/donation-process', name: 'donation_process')]
    public function donationProcess(Request $request)
    {
        $amount = (int) ($request->get('free-amount') ?: $request->get('amount'));
        $monthly = (bool) $request->get('monthly');
        if (!$amount) {
            return $this->redirectToRoute('index');
        }
        $donation = new Donation();
        $donation->setUser($this->getUser());
        $donation->setStatus($monthly ? Donation::STATUS_MONTHLY_NOT_VALID : Donation::STATUS_PUNCTUAL_NOT_VALID);
        $donation->setLocale($request->getLocale());
        $donation->setAmount($amount);
        $donation->setPaymentMethod(Donation::PAYMENT_METHOD_CB);
        $this->entityManager->persist($donation);
        $this->entityManager->flush();
        if ($monthly) {
            $bankAlias = substr($donation->getId() . '_' . (null !== $donation->getUser() ? explode('@', $donation->getUser()->getEmail())[0] : 'anonymous'), 0, 50);
            $userBankAlias = new UserBankAlias();
            $userBankAlias->setUser($donation->getUser());
            $userBankAlias->setBankAlias($bankAlias);
            $donation->setUserBankAlias($userBankAlias);
            $this->entityManager->persist($userBankAlias);
            $this->entityManager->flush();
        } else {
            $userBankAlias = null;
        }
        return $this->paymentService->processPaymentRequest($donation, $userBankAlias);
    }

    #[Route('/{_locale<%app.locales%>}/donation-payment-response/{donation}', name: 'donation_payment_response')]
    public function donationPaymentResponse(Request $request, Donation $donation)
    {
        if ($this->paymentService->processPaymentResponse($request, $donation)) {
            $sendEmail = false; // to avoid mutiple emails if multiple calls
            switch ($donation->getStatus()) {
                case Donation::STATUS_PUNCTUAL_NOT_VALID:
                    $donation->setStatus(Donation::STATUS_PUNCTUAL_VALID);
                    $sendEmail = true;
                    break;
                case Donation::STATUS_MONTHLY_NOT_VALID:
                    $donation->setStatus(Donation::STATUS_MONTHLY_VALID);
                    $sendEmail = true;
                    break;
            }
            $this->entityManager->flush();
            if ($sendEmail && null !== $donation->getUser()) {
                $this->mailerService->sendEmail(
                    EmailLog::TYPE_USER,
                    $this->translator->trans('email.donation_confirmation.subject'),
                    [$donation->getUser()->getEmail()],
                    'donation_confirmation',
                    [
                        'type' => $donation->getStatus() == Donation::STATUS_MONTHLY_VALID ? $this->translator->trans('donation.monthly') : $this->translator->trans('donation.punctual'),
                        'amount' => $donation->getAmount(),
                    ]
                );
            }
        }
    }

    #[Route('/{_locale<%app.locales%>}/donation-payment-error/{donation}', name: 'donation_payment_error')]
    public function donationPaymentError(Donation $donation)
    {
        return $this->render('front/donation/payment-error.html.twig', [
            'donation' => $donation,
        ]);
    }

    #[Route('/{_locale<%app.locales%>}/donation-payment-success/{donation}', name: 'donation_payment_success')]
    public function donationPaymentSuccess(Donation $donation)
    {
        return $this->render('front/donation/payment-success.html.twig', [
            'donation' => $donation,
        ]);
    }
}

templates/front/user/account.html.twig
{% extends 'front/user/layout.html.twig' %}

{% block page_title %}{{ 'front.page.user_account.title'|trans }}{% endblock %}

{% block page_contents %}
    {{ form(accountForm) }}
    <hr class="mt-4 mb-4" />
    <p class="text-center">
        <a href="{{ path('user_account_download_personal_data') }}">{{ 'front.page.user_account.download_personal_data'|trans }}</a>
    </p>
    <hr class="mt-4 mb-4" />
    <p class="text-center">
        <a href="{{ path('user_account_delete_account') }}" onclick="return window.confirm('{{ 'front.page.user_account.delete_account_warning'|trans }}')">{{ 'front.page.user_account.delete_account'|trans }}</a>
    </p>
{% endblock %}

templates/front/user/address.html.twig
{% extends 'front/user/layout.html.twig' %}

{% block page_title %}{{ 'front.page.user_address.title'|trans }}{% endblock %}

{% block page_contents %}
    <p class="text-center">
        {{ 'front.page.user_address.only_forcompensations'|trans }}
    </p>
    {{ form(addressForm) }}
{% endblock %}

templates/front/user/compensation.html.twig
{% extends 'front/user/layout.html.twig' %}

{% block page_title %}{{ 'front.page.user_compensation.title'|trans }}{% endblock %}

{% block page_contents %}
    {% include 'front/user/partial/total-cumul-summary.html.twig' %}
    <p class="text-center">
        {% if gifts|length > 0 %}
            {{ 'front.page.user_compensation.intro_ok'|trans }}
        {% else %}
            {{ 'front.page.user_compensation.intro_ko'|trans }}
        {% endif %}
    </p>
    {% if gifts|length > 0 %}
        <form method="post" id="compensation-form" class="{% if app.user.address == null %}no-user-address{% endif %}">
            <div class="row mb-3">
                {% for gift in gifts %}
                    <div class="col-md-4 mb-2">
                        <label class="card {% if gift.donationAmountNeeded > app.user.cumul %}disabled{% endif %}">
                            <div class="card-body">
                                <input type="radio" name="gift" class="form-check-input" value="{{ gift.id }}" {% if gift.donationAmountNeeded > app.user.cumul %}disabled{% endif %} />
                                <img class="card-img-top" src="{{ asset('images/gift/' ~ gift.image2) }}" alt="{{ gift.name }}">
                                <h3>
                                    {{ gift.name }}
                                    <div class="float-end">
                                        {{ gift.donationAmountNeeded }} &euro;
                                    </div>
                                </h3>
                                <p class="card-text">
                                    {{ gift.description }}
                                </p>
                                {% if gift.variations|length > 0 %}
                                    <p class="card-text text-center">
                                        <select name="variation_{{ gift.id }}" {% if gift.donationAmountNeeded > app.user.cumul %}disabled{% endif %}>
                                            {% for variation in gift.variations %}
                                                <option value="{{ variation.id }}">{{ variation.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </p>
                                {% endif %}
                            </div>
                        </label>
                    </div>
                {% endfor %}
            </div>
            {% if app.user.address == null %}
                <div class="alert alert-warning text-center mb-4" role="alert">
                    <strong>
                        {{ 'front.page.user_compensation.must_add_address'|trans }}
                        <a href="{{ path('user_address') }}">{{ 'front.page.user_compensation.here'|trans }}</a>
                    </strong>
                </div>
            {% else %}
                <p>
                    {{ 'front.page.user_compensation.send_to'|trans }} :
                    <strong>{{ app.user.address }}</strong>
                </p>
                <p>
                    <a href="{{ path('user_address') }}">{{ 'front.page.user_compensation.edit_address'|trans }}</a>
                </p>
                <p>
                    {{ 'front.page.user_compensation.address_conservation_info'|trans }}
                </p>
                <div class="form-check mb-3">
                    <input class="form-check-input" type="checkbox" value="1" name="keep_address" id="keep_address">
                    <label class="form-check-label" for="keep_address">
                        {{ 'front.page.user_compensation.keep_address'|trans }}
                    </label>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="comment">{{ 'front.page.user_compensation.comment'|trans }}</label>
                    <textarea name="comment" class="form-control"></textarea>
                </div>
            {% endif %}
            <div class="mb-3">
                <button type="submit" class="btn btn-primary">{{ 'front.page.user_compensation.submit'|trans }}</button>
            </div>
        </form>
    {% endif %}
{% endblock %}

templates/front/user/dashboard.html.twig
{% extends 'front/user/layout.html.twig' %}

{% block page_title %}{{ 'front.page.user_dashboard.title'|trans }}{% endblock %}

{% block page_contents %}
    <h2>{{ 'front.page.user_dashboard.title_donations'|trans }}</h2>
    {% include 'front/user/partial/total-cumul-summary.html.twig' %}
    <p class="text-center mt-3">
        <a href="{{ path('index') }}" class="btn btn-primary">{{ 'front.page.user_dashboard.new_donation'|trans }}</a>
    </p>
    <p class="text-center mt-3">
        <a href="{{ path('user_compensation') }}" class="btn btn-primary">{{ 'front.page.user_dashboard.ask_compensations'|trans }}</a>
    </p>
    <p class="mt-5">
        {{ 'front.page.user_dashboard.privacy_message_1'|trans }}
    </p>
    <p>
        {{ 'front.page.user_dashboard.privacy_message_2'|trans }}
    </p>
{% endblock %}

templates/front/user/history.html.twig
{% extends 'front/user/layout.html.twig' %}

{% block page_title %}{{ 'front.page.user_history.title'|trans }}{% endblock %}

{% block page_contents %}
    <div class="row">
        <div class="col-xl-6  mt-4">
            <h2>{{ 'front.page.user_history.title_donations'|trans }}</h2>
            {% if donations|length > 0 %}
                <table class="table mb-5">
                    <thead>
                    <tr>
                        <th scope="col">{{ 'fields.date'|trans }}</th>
                        <th scope="col">{{ 'fields.amount'|trans }}</th>
                        <th scope="col">{{ 'fields.status'|trans }}</th>
                        <th scope="col">{{ 'fields.payment_method'|trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for donation in donations %}
                        <tr>
                            <td>{{ donation.createdAt|format_datetime('long', 'short', locale='fr') }}</td>
                            <td>{{ donation.amount }} &euro;</td>
                            <td>{{ donation.statusString|trans }}</td>
                            <td>{{ donation.paymentMethodString|trans }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>{{ 'front.page.user_history.no_donations'|trans }}</p>
            {% endif %}
        </div>
        <div class="col-xl-6 mt-4">
            <h2>{{ 'front.page.user_history.title_compensations'|trans }}</h2>
            {% if donations|length > 0 %}
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">{{ 'fields.date'|trans }}</th>
                        <th scope="col">{{ 'fields.gift'|trans }}</th>
                        <th scope="col">{{ 'fields.gift_variation'|trans }}</th>
                        <th scope="col">{{ 'fields.status'|trans }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for compensation in compensations %}
                        <tr>
                            <td>{{ compensation.createdAt|format_datetime('long', 'short', locale='fr') }}</td>
                            <td>{{ compensation.gift }}</td>
                            <td>{{ compensation.giftVariation }}</td>
                            <td>{{ compensation.statusString|trans }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>{{ 'front.page.user_history.no_compensations'|trans }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/front/user/layout.html.twig
{% extends 'front/base.html.twig' %}

{% block content %}
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto px-sm-2 px-0">
                {% include 'front/user/partial/sidebar.html.twig' %}
            </div>
            <div class="col py-3">
                <h1>{% block page_title %}{% endblock %}</h1>
                {% include "front/partial/flashes.html.twig" %}
                {% block page_contents %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/front/user/login.html.twig
{% extends 'front/layout.html.twig' %}

{% block page_title %}{{ 'front.form.user.login.title'|trans }}{% endblock %}

{% block page_contents %}
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <form action="{{ path('user_login') }}" method="post">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
        <div class="mb-3">
            <label for="username" class="form-label required">{{ 'fields.email'|trans }}</label>
            <input type="email" id="username" name="_username" class="form-control" value="{{ last_username }}" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label required">{{ 'fields.password'|trans }}</label>
            <input type="password" id="password" name="_password" class="form-control" required>
        </div>
        <input type="hidden" name="_target_path" value="{% if app.request.get('redirect') %}{{ app.request.get('redirect') }}{% else %}{{ path('user_dashboard') }}{% endif %}">
        <div class="mb-3">
            <button type="submit" class="btn btn-primary">{{ 'front.form.user.login.submit'|trans }}</button>
        </div>
        <p class="text-center">
            <a href="{{ path('user_forgot_password_request') }}" data-ajax-modal>{{ 'front.form.user.login.forgot_password_request'|trans }}</a>
        </p>
    </form>
{% endblock %}

templates/front/user/register.html.twig
{% extends 'front/layout.html.twig' %}

{% block page_title %}{{ 'front.form.user.register.title'|trans }}{% endblock %}

{% block page_contents %}
    {{ form(registrationForm) }}
{% endblock %}